### ISSUE TITLE
will there be a 1.20 version?

### ISSUE THREAD

**Issue by r0sh11** [PneumonoIsNotAvailable/Umbrellas#1]
I really liked your mods, but I'm playing on 1.20 and would like to know if there will be a 1.20 version of the mod?

**Comment by PneumonoIsNotAvailable** [comment]
I wasn't originally planning to, but it doesn't sound too hard, sure!

**Comment by PneumonoIsNotAvailable** [comment]
Did it!
[Umbrellas 1.20](https://modrinth.com/mod/pneumono_umbrellas/version/1.0.2+1.20)
[PneumonoCore 1.20](https://modrinth.com/mod/pneumono_core/version/1.0.9+1.20)

**Comment by r0sh11** [comment]
thank you very much!!
