### ISSUE TITLE
Suggestion: Alternative Animals Umbrella Recipe

### ISSUE THREAD

**Issue by JasdanVM** [PneumonoIsNotAvailable/Umbrellas#10]
Here's a slightly more immersive recipe for the Animals Umbrella, that's also, a lot less disturbing, lol.
![animals_umbrella_new](https://github.com/user-attachments/assets/e5564499-373b-426c-a62c-2e4a836a3f33)

**Comment by JasdanVM** [comment]
![_tag_item_c_plushies_cat](https://github.com/user-attachments/assets/60f667fd-80ba-4d22-9a07-b4de25878224)
![_tag_item_c_plushies_axolotl](https://github.com/user-attachments/assets/49a2d505-fe36-4f74-9be9-91f917bc67df)

**Comment by JasdanVM** [comment]
```
{
  "type": "minecraft:crafting_shaped",
  "category": "equipment",
  "group": "extra_umbrellas",
  "key": {
	"C": {
      "tag": "c:plushies_cat"
    }, 
    "A": {
      "tag": "c:plushies_axolotl"
    },
    "R": {
      "item": "minecraft:red_wool"
    },
    "S": {
      "item": "minecraft:stick"
    },
    "U": {
      "tag": "umbrellas:umbrellas"
    }
  },
  "pattern": [
    "CRA",
    "RUR",
    " S "
  ],
  "result": {
    "item": "umbrellas:animals_umbrella"
  },
  "show_notification": true
}
```

[c.zip](https://github.com/user-attachments/files/17091570/c.zip)

**Comment by JasdanVM** [comment]
I personally would also add Gold Nuggets to the recipe, btw.

**Comment by PneumonoIsNotAvailable** [comment]
Although plushies make more sense than an axolotl bucket, changing the recipe to this would make installing a plushies mod required in order to craft the umbrella, which I don't really want to do. I might change the recipe to use other colored wool to represent the animals though!

**Comment by JasdanVM** [comment]
> Although plushies make more sense than an axolotl bucket, changing the recipe to this would make installing a plushies mod required in order to craft the umbrella, which I don't really want to do. I might change the recipe to use other colored wool to represent the animals though!

I understand that, it's why I suggested it as an "Alternative..." Recipe, I don't want to suggest anything complex, but maybe this recipe could activate if a plushie mod or Simple Hats is installed (otherwise using the more simple wool option).
In any case, it's nice players won't have to stick a poor Axolotl to an Umbrella anymore.

**Comment by JasdanVM** [comment]
Uh, this is a little silly, but also a simple solution, you could just add the two plushies into the mod, like you do in Pneumono's Stuff, you kinda already have the models, and this way you would ensure the plushie model fully matches was shown in the umbrella.
