### ISSUE TITLE
umbrellas aren't preventing burning in the sun/rain damage with origins mod

### ISSUE THREAD

**Issue by zomnope** [PneumonoIsNotAvailable/Umbrellas#3]
i still start to burn in the sun as a phantom holding an umbrella (both main hand and off-hand), same is true for enderian in rain

it also doesn't prevent zombies from burning in the sun
![2024-01-14_11 00 28](https://github.com/PneumonoIsNotAvailable/Umbrellas/assets/100583743/17cac283-f007-4350-b635-03c5738dfc1e)

i'm using the most recent version as of writing this (1.0.2) on 1.20.1 (fabric loader ver is 0.15.3)

if this is a mistake on my part im very sorry for being a nuisance

**Comment by PneumonoIsNotAvailable** [comment]
Oh my god I'm so sorry I'm so stupid-
The mod is meant to change the skylight detection thingy from "if in sun" to "if in sun and NOT using umbrella", I accidentally made it "if in sun and using umbrella". Thanks so much for going and pointing this out I don't even know how I managed to do that without catching it.
I'll upload a fixed version in a few minutes!
