### ISSUE TITLE
Allow fire blocks to give updrafts 

### ISSUE THREAD

**Issue by Diego13303** [PneumonoIsNotAvailable/Umbrellas#6]
I think this would allow you to use the updraft a lot more often during casual gameplay without having to carry tons of campfires around. Being able to climb a tall ledge by using a flint and steel sounds really fun
If it seems too overpowered it could maybe be its own option in config

**Comment by PneumonoIsNotAvailable** [comment]
Yeah, makes sense.
I haven't really had the energy to work on mods in quite a bit, but when it comes back I'll probably add this

**Comment by PneumonoIsNotAvailable** [comment]
Will be in the next update, which will hopefully release in the next few days (sorry it's taken so long, my motivation drought was immediately followed by exams!)
